version: '3.8'
services:
  app:
    container_name: book_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Exercise3:/app
      - /app/node_modules
