version: '3.8'
services:
  app:
    container_name: social_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Exercise4:/app
      - /app/node_modules
      # Mount package.json and package-lock.json for dependency management
      - ./Exercise4/package.json:/app/package.json
      - ./Exercise4/package-lock.json:/app/package-lock.json
